SM-1444: Fix Windows GNU Builds
bitwarden/sdk pull request #1053
Opened 2024-09-17 13:08 UTC by coltonhurst

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-1444

## 📔 Objective

Windows GNU builds are currently broken due to a bug in [rustls-platform-verifier](https://github.com/rustls/rustls-platform-verifier) when LTO is turned on.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-18 11:31 UTC, michalchecinski requested changes
I've added two renaming suggestions to reflect better which systems they should run for. This will result in better visibility of whether the appropriate build step has been run.

2024-09-18 11:31 UTC, michalchecinski commented on .github/workflows/build-rust-cross-platform.yml
>        - name: Build Rust for - ${{ matrix.settings.target }}
```suggestion
      - name: Build Rust for musl
```

2024-09-18 11:31 UTC, michalchecinski commented on .github/workflows/build-rust-cross-platform.yml
>        - name: Build Rust for - ${{ matrix.settings.target }}
```suggestion
      - name: Build Rust for windows-gnu
```

2024-09-18 15:22 UTC, coltonhurst commented
@michalchecinski I think it might be beneficial to leave the explicit targets as is?

For `musl`, it could be two different targets, `x86_64-unknown-linux-musl` or `aarch64-unknown-linux-musl`. If we just make it `Build rust for musl` it won't be immediately obvious which architecture it is.

2024-09-19 08:40 UTC, michalchecinski approved these changes

2024-09-19 12:13 UTC, merged