[PM-12431] Temporarily un-export bitwarden_fido
bitwarden/sdk pull request #1072
Opened 2024-09-20 19:17 UTC by coltonhurst

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12431

## 📔 Objective

Temporarily un-export `bitwarden-fido`. We can't release crates for `1.0` because:

- `bitwarden-fido` currently relies on dependencies that are GitHub repositories
- `bitwarden-fido` is not yet released (same with the aforementioned dependencies)

**NOTE**: This will break CI, this should only be merged when we are ready to do 1.0 releases of `bitwarden`, `bws`, etc. It should quickly be followed up with the following PR, after release, which reverses this to fix builds:

{ add PR link when created }

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-23 06:54 UTC, coroiu reviewed
Lots of build errors?

2024-09-23 08:23 UTC, Hinton requested changes
You need to remove bitwarden-fido from the cargo.toml

2024-09-26 12:45 UTC, Hinton approved these changes

2024-09-26 12:52 UTC, coltonhurst commented
> Lots of build errors?

Hey @coroiu, yes, lots of build errors 😅

Please see the PR description

2024-09-26 16:04 UTC, vgrassia approved these changes

2024-09-26 16:05 UTC, merged