Sm 989 create build pipeline for the python language wrapper
bitwarden/sdk pull request #369
Opened 2023-11-27 16:17 UTC by tangowithfoxtrot

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Package the Python SDK so that it can be published to [PyPI.org](pypi.org).

## Code changes

- **`.github/workflows/build-python-wheels.yml`:** create wheels for Linux, macOS, and Windows (AMD64-only). A sdist is also created for other platforms.
- **`languages/python/BitwardenClient/__init__.py`:** export functions and classes for autocompletion in IDEs and the interactive Python interpreter
- **`languages/python/pyproject.toml`**: replaces `setup.py`, which is no longer officially supported. This uses Maturin to build the Rust shared-object library that will be bundled with the SDK.
- **`languages/python/setup.py`**: replaced by `pyproject.toml`

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)

2023-11-29 10:06 UTC, michalchecinski requested changes

2023-11-29 10:06 UTC, michalchecinski commented on .github/workflows/build-python-wheels.yml
> +          path: ${{ github.workspace }}/target/wheels/BitwardenClient-*.tar.gz
New line missing.

2023-11-29 15:18 UTC, michalchecinski submitted a review, later dismissed

2023-11-30 10:45 UTC, michalchecinski submitted a review, later dismissed

2023-11-30 17:38 UTC, Hinton commented
Can we extract the crate changes to a separate PR. I think we would want to spend some time figuring out the appropriate defaults.

2023-12-05 12:44 UTC, dani-garcia commented
For reference, the PR with the Rustls crate changes is here: https://github.com/bitwarden/sdk/pull/374

2024-01-08 19:29 UTC, dani-garcia commented on languages/python/example.py
> +organization_id = os.getenv("BWS_ORG_ID")
Minor thing, but could we change these env variables to be the same we use on the other languages? That way it's easier to test them all at the same time. We could also use env variables for the api and identity URLs.

These are the names we're using with the rest of integrations:
https://github.com/bitwarden/sdk/blob/679673096254e108fa0d71f65bf8fa28ba9679f5/languages/go/example/example.go#L13-L19

2024-01-10 17:21 UTC, Thomas-Avery requested changes
Looks good, one minor recommendation.

2024-01-10 17:27 UTC, Thomas-Avery approved these changes

2024-01-11 15:12 UTC, michalchecinski approved these changes

2024-01-18 15:09 UTC, merged