[DEVOPS-1711] Add Docker image for bws versioning for release workflow
bitwarden/sdk pull request #573
Opened 2024-02-02 12:46 UTC by michalchecinski

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Add docker publish to `release-cli.yml` workflow.

## Code changes

- **.github/workflows/release-cli.yml:** Add docker publish job to `release-cli.yml` workflow.
- **.github/workflows/build-cli-docker.yml** Remove unused input. Publish docker only if building for publish branch

## Before you submit

- Please add **unit tests** where it makes sense to do so

2024-02-05 14:19 UTC, vgrassia requested changes

2024-02-05 14:19 UTC, vgrassia commented on .github/workflows/release-cli.yml
> +      - setup
```suggestion
    needs: setup
```

2024-02-05 14:19 UTC, vgrassia commented on .github/workflows/release-cli.yml
> +          DRY_RUN: ${{ github.event.inputs.release_type == 'Dry Run' }}
```suggestion
          DRY_RUN: ${{ inputs.release_type == 'Dry Run' }}
```

2024-02-05 14:19 UTC, vgrassia commented on .github/workflows/release-cli.yml
> +          push: ${{ github.event.inputs.release_type != 'Dry Run' }}
```suggestion
          push: ${{ inputs.release_type != 'Dry Run' }}
```

2024-02-05 15:50 UTC, vgrassia approved these changes

2024-02-06 04:47 UTC, tangowithfoxtrot approved these changes

2024-02-06 17:02 UTC, merged