[DEVOPS-1750] Fix go release
bitwarden/sdk pull request #646
Opened 2024-03-01 18:18 UTC by michalchecinski

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **.github/workflows/build-rust-cross-platform.yml:** Add ARM64 linux build
- **.github/workflows/release-go.yml** Download precompiled C artifacts and place them in the repo

## Before you submit

- Please add **unit tests** where it makes sense to do so

2024-03-06 18:58 UTC, vgrassia requested changes

2024-03-06 18:58 UTC, vgrassia commented on .github/workflows/build-rust-cross-platform.yml
> +          #   target: aarch64-unknown-linux-gnu
Should this still be commented out?

2024-03-06 18:58 UTC, vgrassia commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```suggestion
          branch: ${{ inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```

2024-03-06 18:58 UTC, vgrassia commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```suggestion
          branch: ${{ inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```

2024-03-06 18:58 UTC, vgrassia commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```suggestion
          branch: ${{ inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```

2024-03-06 18:58 UTC, vgrassia commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```suggestion
          branch: ${{ inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```

2024-03-06 18:58 UTC, vgrassia commented on .github/workflows/release-go.yml
> +      #     path: temp/linux-arm64
Should this still be commented out?

2024-03-06 18:58 UTC, vgrassia commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```suggestion
          branch: ${{ inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
```

2024-03-11 15:49 UTC, michalchecinski commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
Fixed.

2024-03-11 15:49 UTC, michalchecinski commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
Fixed.

2024-03-11 16:13 UTC, michalchecinski commented on .github/workflows/release-go.yml
> +          branch: ${{ github.event.inputs.release_type == 'Dry Run' && 'main' ||  github.ref_name }}
Fixed.

2024-03-11 16:43 UTC, vgrassia approved these changes

2024-03-11 16:43 UTC, merged