[DEVOPS-1751] Pipeline for publishing java sdk to gradle
bitwarden/sdk pull request #740
Opened 2024-04-26 10:59 UTC by michalchecinski

## Type of change

```
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [x] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

## Code changes

- **.github/workflows/build-java.yml:** Run build on `rc` and `hotfix-rc` and on PR. Change Publish task to package.
- **.github/workflows/publish-java.yml** Add Publish workflow
- **.github/workflows/version-bump.yml** Add Java SDK to version bump workflow
- **languages/java/build.gradle** Change name of the package to `sdk-secrets`. Add `https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/` as repository to publish.

## Before you submit

- Please add **unit tests** where it makes sense to do so

2024-04-26 21:12 UTC, mzieniukbw requested changes
<del>I don't think the intention was to make this Java sdk to be Secrets Manager specific.</del>
See below for my other comments

2024-04-26 21:12 UTC, mzieniukbw commented on languages/java/build.gradle
We should publish with java docs (and optionally source code), maybe add:
```
java {
    withJavadocJar()
    withSourcesJar()
}
```

2024-04-26 21:12 UTC, mzieniukbw commented on languages/java/build.gradle
> +                artifactId = 'sdk-secrets'
i though this sdk repo is not specific to secrets manager, but it's for everyone ?

2024-05-01 13:54 UTC, mimartin12 reviewed
Nothing from my side that @mzieniukbw hasn't already by brought up 👍

2024-05-07 11:49 UTC, michalchecinski commented on .github/workflows/build-java.yml
>            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Right! Good catch.

2024-05-07 11:50 UTC, michalchecinski commented on .github/workflows/build-java.yml
> +          arguments: package
Fixed 😃

2024-05-07 20:41 UTC, mzieniukbw approved these changes
lgtm

2024-05-10 06:37 UTC, mzieniukbw submitted a review, later dismissed

2024-05-10 14:20 UTC, mimartin12 approved these changes

2024-05-10 14:20 UTC, merged