Extract encrypt/decrypt refactor from state PR
bitwarden/sdk pull request #85
Opened 2023-07-03 12:59 UTC by Hinton

## Type of change

```
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Extracted from #64

## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)

2023-07-03 13:10 UTC, dani-garcia commented on crates/bitwarden/src/secrets_manager/secrets/secret_response.rs
> +            .decrypt(enc, &org_id)?;
I assumed that the note field would always be present, even if it's an empty string. The secret create request requires it at least, and the bws cli just sets it to an empty string when not specified: https://github.com/bitwarden/sdk/blob/master/crates/bitwarden-api-api/src/models/secret_create_request_model.rs.

If the field could be missing, we'd have to change this to:
```rust
        let note: Option<String> = response
            .note
            .map(|n| Ok(n.parse::<CipherString>()?.decrypt(enc, &org_id)?))
            .transpose()?;
```

2023-07-03 13:20 UTC, Hinton commented on crates/bitwarden/src/secrets_manager/secrets/secret_response.rs
> +            .decrypt(enc, &org_id)?;
That seems to be an accurate assumption. Seems I miss-remembered how it worked. Not going to be the case for ciphers though and we should be vigilant.

2023-07-03 14:13 UTC, MGibson1 requested changes

2023-07-05 14:06 UTC, Hinton commented on crates/bitwarden/src/secrets_manager/secrets/secret_response.rs
> +            .decrypt(enc, &org_id)?;
I don't believe it's a regression though, but something for us to keep track of and try and iterate on.

2023-07-05 17:08 UTC, MGibson1 commented on crates/bitwarden/src/crypto.rs
> +impl<T: Decryptable<Output>, Output, Id: Hash + Eq + Copy> Decryptable<HashMap<Id, Output>>
🤔 should this be `Clone`? `Copy` is good enough for the `Uuid` we use today, but is there a good reason it _has_ to be?

2023-07-06 12:28 UTC, dani-garcia approved these changes

2023-07-07 13:20 UTC, MGibson1 commented on crates/bitwarden/src/crypto.rs
> +impl<T: Decryptable<Output>, Output, Id: Hash + Eq + Copy> Decryptable<HashMap<Id, Output>>
🤦 got those backward

2023-07-07 13:26 UTC, MGibson1 commented on crates/bitwarden/src/secrets_manager/secrets/secret_response.rs
> +            .decrypt(enc, &org_id)?;
fair, it's not as far as I can tell

2023-07-07 13:26 UTC, MGibson1 approved these changes

2023-07-07 14:28 UTC, merged