[SM-1268] Review Java docs
bitwarden/sdk pull request #871
Opened 2024-07-03 15:48 UTC by mzieniukbw

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/SM-1268

## 📔 Objective

Review Java language docs.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-07-03 23:08 UTC, Thomas-Avery requested changes
Looks good!

2024-07-03 23:08 UTC, Thomas-Avery commented on languages/java/README.md
>  # Delete secret or project
```suggestion
### Delete secret or project
```

2024-07-05 16:45 UTC, Thomas-Avery requested changes
Was able to follow the install guide and run this locally on macOS.

One formatting suggestion for consistency.

2024-07-05 16:45 UTC, Thomas-Avery commented on languages/java/README.md
> +```
```suggestion
### Get secret

```java
var secretResponse = bitwardenClient.secrets().get(secretId);
```
```

2024-07-05 20:21 UTC, Thomas-Avery commented on languages/java/README.md
> +
Needs closing ``` 

I think the suggestion didn't read the closing right earlier.

2024-07-05 20:30 UTC, mzieniukbw commented on languages/java/README.md
> +
Nice spot, fixed!

2024-07-05 21:09 UTC, Thomas-Avery approved these changes
LGTM

2024-07-06 00:02 UTC, mzieniukbw commented
@Thomas-Avery Do we need QA testing, since i have updated the Java build scripts ?
At the moment it is hard to even sanity check, since the Java build GH Action does not include the packaged Jar as artifact.

2024-07-09 09:57 UTC, dani-garcia approved these changes

2024-07-09 17:04 UTC, merged